### ISSUE TITLE
How to change default Rofi activation keybind?

### ISSUE THREAD

**Issue by itsthedevman** [archcraft-os/archcraft-i3wm#1]
Greetings! First off, thank you so much for creating this. I've been loving it so far. 

I'm a bit stuck. I can't seem to find where to change the rofi activation keybind from `Mod4` (`win`). I don't see it in i3's config and I've searched the codebase for that key and for calls to rofi but I'm not finding it. 

Thank you for your time!

**Comment by MAKROFREEK** [comment]
Check the very first and second line of the i3 config

**Comment by itsthedevman** [comment]
My apologies, I should've clarified. I'm not looking to change the default mod key. I would like to change it so Rofi activates via `win+D` instead of `win`. 

Thank you for your time!

**Comment by riosgabriel** [comment]
@itsthedevman you can change the rofi keybinding [here](https://github.com/archcraft-os/archcraft-i3wm/blob/main/files/config.d/02_keybindings.conf#L56)
